# Generated by Django 3.2.25 on 2024-09-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentString',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='postString',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
