# Generated by Django 3.2.25 on 2024-09-30 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20240930_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='facebook.post'),
            preserve_default=False,
        ),
    ]
